version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB=DATABASE: nest-course

  postgres:
    container_name: pgindie
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
    - /data/pgindie:/data/postgres
    env_file:
    - docker.env
    networks:
    - pgindie

  test-db:
    container_name: test_db
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass123
    env_file:
    - docker.env
  
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - pgindie

networks:
  pgindie:
    driver: bridge